### PR TITLE
Create ForbiddenHttpException.php

### PR DESCRIPTION
**Pull request by jtheuerkauf**
Do-over-over of #3 and #4 (dedicated upstream branch)
Add Exception class with formal "Forbidden" name for 403

### CODE REVIEW

**Review by Cliabhach — APPROVED** [review]
Generally looks ok. Let's get it in.

**Comment by Cliabhach** [comment]
I've tagged 1.0.4 (no 1.0.3, since I noticed you already had one and I might as well try to make upgrades a little smoother).

**Comment by jtheuerkauf** [comment]
Sounds good to me. Anything in particular i should do in my fork? Pull the new tag?

**Comment by Cliabhach** [comment]
You could, and then use that in your project. The next step for publishing is to tell packagist that there's a new tag.

I'll ask if I can get temporary publishing permissions but (unfortunately) no guarantee that will be done anytime soon.

**Comment by jtheuerkauf** [comment]
Go for it. i just signed up, so i might tinker with publishing mine as a replacement ... If i go forward with that, would this one need an update as abandoned and suggest mine? Or does packagist figure that out?

**Comment by Cliabhach** [comment]
It's been a while since I checked but I think it's all manual. The proper flow is to mark this package as deprecated on packagist, link to your fork from our README, and then archive this github repository.

I think there's also another option I can ask about, where we add you as a maintainer to this repository, if that's something you'd be interested in...?

**Comment by jtheuerkauf** [comment]
Sure, if you have the time/interest to check into it, i'm willing. Thanks for your help with this.

-------- Original Message --------

**Comment by Cliabhach** [comment]
Ok, I asked around, here's what I've got: the best path forward is for you to rename the namespace in your fork from 'Fuzz' to something else, and then you can go ahead and publish that on packagist.

I'll add a message to this README linking to your fork and ask the org admin to archive the repository.

**Comment by jtheuerkauf** [comment]
Sounds like a plan. Thanks for following up. i appreciate the help.

Joe Theuerkauf
------- Original Message -------

**Pull request merged**
